# Generated by Django 4.0.4 on 2022-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CNIC',
            field=models.IntegerField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone_No',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
